name: flutter_nearby_connections_example
description: Demonstrates how to use the flutter_nearby_connections plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

version: 1.0.0+0

dependencies:
  flutter:
    sdk: flutter
  path: any
  flutter_styled_toast:
  flutter_nearby_connections:
  cupertino_icons:
  bubble:
  nanoid:
  sqflite:
  intl:
  pointycastle:
  shared_preferences:
  provider:
  flutter_secure_storage:
  encrypt:
  asn1lib:
  local_auth:
  file_picker:
  open_filex:
  permission_handler:
  path_provider:

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true