name: flutter_nearby_connections_example
description: Demonstrates how to use the flutter_nearby_connections plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_styled_toast: ^2.0.0
  flutter_nearby_connections: ^1.0.11
  cupertino_icons: ^1.0.2
  flutter_udid: ^2.0.0
  bubble: ^1.2.1
  nanoid: ^1.0.0
  sqflite: ^2.0.0+3
  intl: ^0.19.0
  pointycastle: ^3.0.1
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  flutter_secure_storage:
  encrypt: ^5.0.3
  asn1lib:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true