name: flutter_nearby_connections_example
description: Demonstrates how to use the flutter_nearby_connections plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

version: 1.0.0+0

dependencies:
  flutter:
    sdk: flutter
  path: any
  flutter_styled_toast: ^2.2.1
  flutter_nearby_connections: ^1.1.2
  cupertino_icons: ^1.0.8
  bubble: ^1.2.1
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  pointycastle: ^3.9.1
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  encrypt: ^5.0.3
  asn1lib: ^1.5.3
  local_auth: ^2.3.0
  file_picker: ^8.1.2
  open_filex: ^4.5.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.4  web_socket_channel: ^2.2.0
  nanoid: ^1.0.0
  flutter_sound: any
  just_audio: ^0.9.14
  pdf: ^3.11.1

  just_audio: ^0.9.42
  record: ^4.4.4
  audioplayers: ^6.1.0
  device_info_plus: ^11.2.0



dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true